name: Test Project
on: push
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      # See NOTE 1
      - name: Get code
        uses: actions/checkout@v4
      # See NOTE 2
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0




# NOTE 1
# We need to get the code from the repo, because rememeber that all of this CI/CD stuff runs on a VM (the runner),
# an ubuntu VM in this case, and that VM of course does not have the code,
# so we need to provide the machine with the project code.



# NOTE 2
# The ubuntu runner comes with node preinstalled (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)
# but we're installing it anyway just to show how it would be done, we also picked a more recent node version just for fun.

# Why we need to use Node anyway, you ask?
# Remember that the goal of this workflow is to, on every push to the remote repo
# execute the -unit- tests that the devs created. We are automating that testing and ensuring it is tested on every push (CI).
# And because in this case this is a React app -which uses node-, we need to have/use Node on the runner...